# Travis CI
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0

before_script:
  - chmod a+x script/cibuild
  - chmod a+x script/console
  - chmod a+x script/fmt
  - chmod a+x script/release
script: "script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email: false

cache: bundler
sudo: false
